Repository Comma-in-the-schedule/ai_server_repo, pull requests merged in 2025-02, with the labels that each got.

#4 feat: data_collector 추가, routes, init 수정 - [AI/#3]
  .gitignore
  app/__init__.py
  app/routes.py
  app/services/data_collector.py
  requirements.txt
Labels: 기능 추가

#7 [AI - #5] - snippet 수집 기능 구현
  app/services/google_custom_search.py
Labels: 기능 추가

#8 [AI - #6] 설명 생성 기능 구현
  app/services/openai_processor.py
  requirements.txt
Labels: 기능 추가

#10 [AI - #9] openAI 기반 추천 기능 구현
  app/services/recommender.py
Labels: 기능 추가

#12 feat: services 파일 연동되게 수정, routes.py, __init__.py 수정
  app/__init__.py
  app/routes.py
  app/services/data_collector.py
  app/services/google_custom_search.py
  app/services/openai_processor.py
  app/services/recommender.py
Labels: 리팩토링

#15 [AI - #13] API 엔드포인트 통합 및 메인 코드 로직 수정
  app/__init__.py
  app/routes.py
  app/services/data_collector.py
  app/services/google_custom_search.py
  app/services/openai_processor.py
  app/services/recommender.py
Labels: 리팩토링

#17 feat: 날짜 처리 함수 추가 및 프롬프트 수정
  app/__init__.py
  app/services/recommender.py
Labels: 기능 추가

#20 [AI - #14] API 응답 구현
  app/routes.py
  app/services/data_collector.py
  app/services/google_custom_search.py
Labels: 기능 추가

#25 [AI - #24] 추천 여가 활동을 리스트 형태로 반환하도록 수정
  app/routes.py
  app/services/data_collector.py
  app/services/google_custom_search.py
  app/services/openai_processor.py
  app/services/recommender.py
Labels: 리팩토링

#27 다중 카테고리 반환 추가
  app/routes.py
Labels: 기능 추가

#31 [AI - #23, #30] services 폴더 구조 변경 및 파일 이름 변경, 분할
  app/services/data_collectors/naver_collector.py
  app/services/description_generator.py
  app/services/period_processor.py
  app/services/recommender.py
  app/services/snippets_collector.py
Labels: 리팩토링

#34 [Hotfix] 에러 원인 파악을 위한 테스트 코드 작성
  app/routes.py
Labels: 버그 수정

#47 [AI - #46] 테스트 목적 코드 제거 및 원본 코드 복구
  app/routes.py
Labels: 리팩토링

#50 [AI -#48, #49] exhibition_collector.py의 일부 코드 routes.py에 이식 및 날짜 형식 변환 함수 구현.
  app/routes.py
  app/services/data_collectors/exhibition_collector.py
  app/services/period_processor.py
Labels: 기능 추가, 리팩토링

#51 feat: 임시 더미 추가
  app/routes.py
Labels: 기능 추가

#53 [AI - #48, #52] 불필요한 코드 및 에러 유발 코드 수정, 날짜 형식 관련 일부 코드 수정
  app/routes.py
  app/services/data_collectors/exhibition_collector.py
  app/services/description_generator.py
  app/services/period_processor.py
Labels: 리팩토링

#55 [AI - #54] 전시회 관련 각종 기능 추가
  app/routes.py
  app/services/data_collectors/exhibition_collector.py
  app/services/data_collectors/naver_collector.py
  requirements.txt
Labels: 기능 추가

#58 feat: 더미데이터 삭제
  app/routes.py
  app/services/data_collectors/exhibition_collector.py
Labels: 리팩토링

#62 [AI - #61] 인덴트 형식 통일 및 불필요한 코드 제거
  app/__init__.py
  app/services/data_collectors/exhibition_collector.py
  app/services/data_collectors/naver_collector.py
  app/services/description_generator.py
  app/services/period_processor.py
  app/services/recommender.py
  app/services/snippets_collector.py
Labels: 리팩토링

#66 [AI - #65] 카카오 api key 변경 및 응답 실패 시 메시지 추가
  app/services/data_collectors/exhibition_collector.py
Labels: 버그 수정
